// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4gllvm_bernoulli_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllvm_gaussian_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllvm_negbin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllvm_poisson_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_bernoulli_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_bernoulli_phylo_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_gaussian_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_gaussian_phylo_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_negbin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_negbin_phylo_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_poisson_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mglmm_poisson_phylo_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4gllvm_bernoulli_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllvm_bernoulli_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllvm_gaussian_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllvm_gaussian_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllvm_negbin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllvm_negbin_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllvm_poisson_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllvm_poisson_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_bernoulli_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_bernoulli_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_bernoulli_phylo_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_bernoulli_phylo_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_gaussian_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_gaussian_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_gaussian_phylo_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_gaussian_phylo_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_negbin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_negbin_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_negbin_phylo_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_negbin_phylo_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_poisson_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_poisson_mod, 0},
    {"_rcpp_module_boot_stan_fit4mglmm_poisson_phylo_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mglmm_poisson_phylo_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_jsdmstan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
