# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("gllvm_bernoulli", "gllvm_gaussian", "gllvm_negbin", "gllvm_poisson", "mglmm_bernoulli", "mglmm_bernoulli_phylo", "mglmm_gaussian", "mglmm_gaussian_phylo", "mglmm_negbin", "mglmm_negbin_phylo", "mglmm_poisson", "mglmm_poisson_phylo")

# load each stan module
Rcpp::loadModule("stan_fit4gllvm_bernoulli_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllvm_gaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllvm_negbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllvm_poisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_bernoulli_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_bernoulli_phylo_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_gaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_gaussian_phylo_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_negbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_negbin_phylo_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_poisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mglmm_poisson_phylo_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
